### ISSUE TITLE
Renderer refactor task list

### ISSUE THREAD

**Issue by Lwmte** [MontyTRC89/TombEngine#1291]
- [x] Pickup notifier has depth issues (sometimes back parts of the pickup model are rendered in front)
- [x] Pickup notifier is not affected by antialiasing and postprocessing
- [x] Antialiasing does not affect inventory
- [ ] SSAO has artifacts around screen borders when camera is really close to the walls
- [x] https://github.com/MontyTRC89/TombEngine/issues/1269
- [x] https://github.com/MontyTRC89/TombEngine/issues/1257
- [x] https://github.com/MontyTRC89/TombEngine/issues/1295
- [x] Odd polygons with wrong textures appear when shooting near transparent faces. These polys disappear as smoke sprites fade away (privately sent project/save to Monty).
