### ISSUE TITLE
60 FPS task list to fix

### ISSUE THREAD

**Issue by Jakub768** [MontyTRC89/TombEngine#1365]
- [ ] sprites/effects such as footprints, gun smoke etc still flicker (goes the same for target highlighter but only when lara runs).
- [ ] when I am in large open area with lots of rooms, the fps dips into 40s/50s (probably the same problem as @JoeyQuint has).
- [ ] when I have a camera with a target, there's a stray frame before it goes back to lara.
- [ ] when on inventory menu, the game timer counts up too fast

**Comment by TrainWrack** [comment]
My comments are here

https://discord.com/channels/1072511394735464498/1117554544776327270/1239337283862269983

**Comment by davidmarr** [comment]
In the title level the strings flicker and tremble (165 Hz)

https://github.com/MontyTRC89/TombEngine/assets/116632612/1980dd5a-d702-4cc8-864c-dd23b2f6e027

**Comment by davidmarr** [comment]
the light from the binoculars is bugged
https://mega.nz/file/6tVF3RxY#_nJnB1YNapHB6-jke4w2ic0R4R_Sux26c3Q6lCgWSSQ

**Comment by davidmarr** [comment]
Jeep parts in water do not show correctly. I tested at 60 fps and at 165 fps.

https://github.com/MontyTRC89/TombEngine/assets/116632612/f072edc8-37ef-411b-9f58-0222fd6b8ef6

https://github.com/MontyTRC89/TombEngine/assets/116632612/29ba05e3-6d81-4a9b-9614-46a660607f71

**Comment by davidmarr** [comment]
By killing enemies with the grenade launcher or similar, the position of enemy pieces flickers. At 165 Hz the position flicker is greater

https://github.com/MontyTRC89/TombEngine/assets/116632612/38b8d293-ef4f-4aae-9971-2bffe9e24c61

https://github.com/MontyTRC89/TombEngine/assets/116632612/6da89db1-3b27-4338-a4fe-4e83cae18595

**Comment by TrainWrack** [comment]
Fish emitter is still not working. Before the fixes they were atleast visible on the ground. Just not moving. Now they are not rendered at all.
The beetles are 60fps now. They look great. 

I can confirm that the  following issues can be closed. They behave the same as the last release now.

 Normal Alphas textures are broken again
 Textures applied on objects with exclude attribute are black
 Textures applied on objects with subtract attribute are flickering

**Comment by TrainWrack** [comment]
Gunflashes still seem 30 fps.

**Comment by davidmarr** [comment]
The flickering of the crosshair on the move is solved. But there are 2 problems. 
In some scenarios if Lara stays with the guns drawn some crosshairs remain visible, even if Lara is not aiming at anyone.
Sometimes it happens that the remaining sights have flickering (I also report this, although the crosshairs should not remain). 
I don't know if it depends on the 60fps branch or the crosshairs have some bug.

https://github.com/MontyTRC89/TombEngine/assets/116632612/52a95943-9bc3-40cf-aecd-8e6e109ee782

**Comment by davidmarr** [comment]
In the grenade explosion, the sprite is buggy

https://github.com/MontyTRC89/TombEngine/assets/116632612/59c15996-d143-4ea4-831d-ed601def7230

![image](https://github.com/MontyTRC89/TombEngine/assets/116632612/abb59589-231a-4d42-94f0-dd7b8f010e2f)

a dummy grenade spawns randomly (thank you @Jakub768)
![image](https://github.com/MontyTRC89/TombEngine/assets/116632612/da9c0f60-fad4-459e-88c8-9350b683e6e1)

**Comment by TrainWrack** [comment]
The turn switch interpolates and you can see it switching over 2 frames.

**Comment by MatieTR** [comment]
Whenever a regular camera with a camera target (plus one of the flybys also has it) is triggered there's a random frame, showing a random part of the level as it switches over.

Video:
https://streamable.com/1a6uae

It also happens when it has to quickly change direction, like when I jump up the block and back down and the camera gets stuck in the column so it has to change position:

https://streamable.com/rht6tk

A rollingball also collapses for a moment, only happening in 60 FPS mode:

https://streamable.com/axjgjz
