### ISSUE TITLE
Refactor floordata parser and get rid of globals

### ISSUE THREAD

**Issue by Lwmte** [MontyTRC89/TombEngine#299]
Currently TEN uses highly unstable approach for reading various block flags, floordata triggers and heights using various globals which are updated every time `GetFloorHeight` function is called. Apart from highly unreadable and appaling quality code, this results e.g. in occasional (around 25-50% of all times) incorrect behaviour on monkeyswing when Lara transitions from room to room, and possibly other collisional bugs.

### Task list

- [x] Get rid of `TriggerIndex` global, refactoring old sequential floordata parser in a way that only actual triggers are kept in old floordata sequences.
- [x] Move all block flags, such as monkey, climb, death, etc. into normal structure, probably along with new floordata struct.
- [x] Remove `TiltXOffset`, `TiltZOffset`, `SplitFloor` and `HeightType` globals and contain them in new `COLL_TEST` struct, along with floor/ceiling heights.
- [x] Remove `DoFloorThings` function which is just a dummy function refreshing aforementioned globals.
- [x] Convert native `GetFloorHeight` function into new function `GetCollTests` which will return `COLL_TEST` struct with all data previously contained in globals from fig. C.
- [x] Remove all occurences of _just-to-be-sure_ `GetFloorHeight` calls and all references to globals from fig. C and put calls to `GetCollTests` instead in same places, rerouting global references to `GetCollTests` return value.
- [x] Resolve inconsistencies between `COLL_INFO` tiltX and tiltZ fields and `COLL_RESULT` `TiltXOffset`/`TilitYOffset` fields.
- [x] Clarify the fate of `OnObject` global.
- [ ] Rename all references to `floor` which is actually a `block`. For example, `GetFloor` to `GetBlock` to make naming consistent with TE.

Currently this development is done on this branch: https://github.com/MontyTRC89/TombEngine/tree/legacy_trigger_refactor
