### ISSUE TITLE
Floordata bugs

### ISSUE THREAD

**Issue by Lwmte** [MontyTRC89/TombEngine#677]
- [ ] 1. gecko: " i got this weird bug where in this room if lara doesn't grab/misses the ledge she clips into a few rooms below"
 https://streamable.com/hbcolv 
 probably related to problem number 2 from #1437 

- [x] 2. ~~Sprint jump glitch:
https://www.youtube.com/watch?v=Zww-e-CxF8E~~

- [ ] 3. Falling through triangular sloped portals with TO1:
https://user-images.githubusercontent.com/3331699/185001883-0775738b-5f76-4913-bfbd-5d8bc22ec4ff.mp4

- [ ] 4. Here's another when Lara surfaces with a jut out platform with water underneath she could jam her head into the wall on the surface - I can't quite replicate it during filming but you could see how it looks with the camera inside the block at the start.
https://youtu.be/JOaov_c-pQk

- [ ] 5. Lara can fall through bridge tilt item which is placed above slope: 

https://user-images.githubusercontent.com/3331699/206312196-9fb659c7-f309-48e8-b752-9d7d0fb62351.mp4

- [ ] 6. An issue with shimmying through a portal with toggle opacity set: https://github.com/MontyTRC89/TombEngine/issues/595

- [ ] 7. Numerous bugs with grabbing / hanging (not sure if `states_tier_3` changes fix those): https://github.com/MontyTRC89/TombEngine/issues/988

- [x] 8. Non-working monkeyswing above diagonally: https://github.com/MontyTRC89/TombEngine/issues/914

- [x] 9. Vaulting in certain setups: https://github.com/MontyTRC89/TombEngine/issues/914391

- [ ]  10. Vaulting requires ugly hack to work in certain contexts (Sezz).

- [x] 11. Saving on bridges teleport: https://github.com/MontyTRC89/TombEngine/issues/834

- [x] 12. Pushables over trapdoors: https://github.com/MontyTRC89/TombEngine/issues/886

- [x] 13. Monkey swing under trap door in stacked room: https://github.com/MontyTRC89/TombEngine/issues/681

- [x] 14. Saving on twoblock platform: https://github.com/MontyTRC89/TombEngine/issues/663

- [x] 15. Lara not going in hanging state when there is a ladder and a crack https://github.com/MontyTRC89/TombEngine/issues/1192

- [x] 16. It's not possible to grab the ledge from backsliding state, if slope is triangulated: https://github.com/MontyTRC89/TombEngine/issues/1212

- [x] 17. Lara rolls into diagonal wall: https://github.com/MontyTRC89/TombEngine/issues/1234 

NOT floordata:

- [ ] 18. Lara can submerge into diagonal wall geometry and die (shifts issue):
https://www.youtube.com/watch?v=Hb8yX3KLIO4

- [ ] 19. When Lara's on a ladder but there is an obstacle in her way, as long as her head is clear she will continue climbing up one step at a time. She refuses to climb down however (climbable wall issue).
https://www.youtube.com/watch?v=yh9ygFxs4T8 (at around 1 minute)

- [ ] 20. Bridge probe failure.
https://youtu.be/LTso-AavzDU?si=1fyz5CbwU_Jm7tbd&t=1815

**Comment by Lwmte** [comment]
https://github.com/MontyTRC89/TombEngine/issues/886 related
