### ISSUE TITLE
Pathfinding enhancements roadmap

### ISSUE THREAD

**Issue by Lwmte** [MontyTRC89/TombEngine#948]
- [ ] Introduce `LOTType` to configure creature pathfinding instead of weird `ZoneType` extension.
- [ ] Introduce new amphibious zone especially for crocodile and possibly rat in future, and use legacy water zone from TR1-3 for other water enemies.
- [ ] Introduce average height value for `Box` struct, so enemies which can't get into corridors with narrow ceilings (e.g. T-Rex, Seth etc.) won't continuously run into them.
